version: '3.8'

services:
  backend:
    image: node:latest
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000" # Választható port, a backend alkalmazás portja
    command: node index.js
    depends_on:
      - db

  frontend:
    image: node:latest
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000" # Választható port, a React alkalmazás portja
    command: npm start
    depends_on:
      - backend

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db

volumes:
  dbdata: